// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    empty
    (
        init => init
        create => create
        cancelOffer => cancel_offer
        acceptOffer => accept_offer
        getLastOfferId => last_offer_id
        getOffer => offer
        getUserOffers => user_offers
        getUserIncomingOffers => user_incoming_offers
        getActiveOffers => get_active_offers
        getUserActiveOffers => get_user_active_offers
        getUserIncomingActiveOffers => get_user_incoming_active_offers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
